### ISSUE TITLE
共有機能・相談ごとにID割り当て、暗号化

### ISSUE THREAD

**Issue by waka320** [jphacks/ng_2406#23]
#20
出力ごとに固有のIDを作成、それを暗号化にしてフロント用のURLにする

**Comment by kabetani-yusei** [comment]
#29 が終わってから取り掛かる。
今の自分の考えとしては、8桁くらいで、最初の4桁はidの番号で最後の4桁はランダムな数字
それをいい感じに暗号化させたい
