### ISSUE TITLE
ローディング改善・１つの応答ずつフロントに送信

### ISSUE THREAD

**Issue by waka320** [jphacks/ng_2406#29]
#25 
１つの応答ずつフロントに送信
まだ応答が残っている時はフロントにそれを知らせる

**Comment by kabetani-yusei** [comment]
今はユーザーからプロンプトを受け取って、リストで各行動とそれに対するアドバイスを送るまでを1つのエンドポイントにしているけれど、
行動の配列を返すエンドポイントと、行動からアドバイスを送るエンドポイントの2つを作成すれば解決しそう
